sudo: required
os: linux
services:
  - docker

before_install:
  - docker build -t tmcelhattan/docker-react -f Dockerfile.dev . 

script:
  - docker run tmcelhattan/docker-react npm run test --no-watch --coverage