sudo: required
os: linux
services:
  - docker

before_install:
  - docker build -t tmcelhattan/docker-react -f Dockerfile.dev . 

script:
  - docker run tmcelhattan/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-716684591783"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"

